### PR TITLE
Include leading '<' + remove leading ' ' when copying messages

### PR DESCRIPTION
**Pull request by progval**
Closes GH-4369.

1. Fix missing leading '<'

Firefox does not seem to select leading (or trailing) characters that are
too small; so this commit sets a very small width, that is still large
enough to be selected.

This commit also adds `display: inline-block`, so the width is not
ignored; but this causes Chrome to ignore the space after `>`, so I made
it a non-breakable space.

An alternative is to make only the leading `only-copy` an
`inline-block`, but I think the non-breakable space is a good idea
regardless.

2. Remove leading ' ' when copying multiple messages

### CODE REVIEW

**Comment by MaxLeiter** [comment]
@xnaas as you reported the bug I'd appreciate your approval here

**Comment by xnaas** [comment]
Brief testing shows that this solves the `<` copy issue on Chromium and Firefox, but the empty space before timestamps (when copying multiple lines) still seems to be present at least when testing on Firefox 98beta and 91.5.0esr (Windows 10). Chromium seems fully sorted out, though.

**Comment by progval** [comment]
oh yeah I missed the second part. Fixed as well now.

**Review by MaxLeiter — APPROVED** [review]

**Comment by xnaas** [comment]
I don't know that there's an solution to is, but I noticed that iOS Safari doesn't get the `<`. Highlighting stuff in general is a massive pain in the ass on iOS though, so probably outside of the scope of this PR.

**Comment by progval** [comment]
You could try replacing `0.01px` with something a little bit bigger

**Comment by brunnre8** [comment]
Thanks Val, as always.

**Pull request merged**
