### PR TITLE
MVP Message Search (WIP)

### PR DESCRIPTION
**Pull request by richrd**
This is not ready, but I'm opening this PR for discussion (issue #109). This is my first contribution so there's probably a lot to do/change/fix etc. This is how it looks like on mobile: https://www.youtube.com/watch?v=jid1v9-jN7k (video is a bit out of date at this point)

What this does:
- Adds a search field to the channel and network header bars (on mobile a search icon is shown, clicking it opens the search field as a dropdown)
- Pressing enter in the field runs the search and navigates the user to the search results page
- Searching from the lobby searches all channels, searching from a channel searches only in that channel
- The search result page allows the search to be refined and shows how many results were found
- The search keyword is highlighted in each search result message
- The backend db search is just a simple `LIKE %keyword%` and is limited to 100 results

Let me know what you think.

### CODE REVIEW

**Comment by richrd** [comment]
Some thoughts:
- We could ditch the search icon on desktop and just show the search field in the header
- We need to do something with the UI if search (logs) are not available
- The dropdown animation could be ditched,  its just unneccessary eyecandy
- It would be really nice to highlight the search term in the message results
- Should the search also apply to nicks?

**Comment by christer88** [comment]
Suggestion: I think it would be nice if it is possible to click on the text line to get you to where it is in the channel, or some other way to show you more than just the single line that had the word you searched for. Sometimes you kind of need to see what happen before and after the text line to understand the context.

**Comment by richrd** [comment]
I agree, thats more or less a must have feature. Its not an easy thing though so it would be good to add it later. I dont know whether this will make it into 3.0 or 3.1 but hopefully sooner than later :)

**Comment by richrd** [comment]
Any comments on this?

**Comment by richrd** [comment]
I'd actually like to close this and reimplement it after vue is released. It would be a lot cleaner to do it after that. Thoughts?

**Comment by McInkay** [comment]
@richrd That would probably make most sense. Thanks for the initial work, and sorry it didn't get in this time.

**Pull request closed without merging**
