### PR TITLE
Support file uploads to dumpinen.com

### PR DESCRIPTION
**Pull request by osm**
This PR makes it possible to configure the clients to upload files to dumpinen.com instead of the self hosted file storage in the lounge.

dumpinen.com is a lightweight file dumping service, kind of like pastebin.com but without ads and the ability to dump all kind of files.

### CODE REVIEW

**Comment by dgw** [comment]
I don't expect building different upload services into core to get much traction with this project (see e.g. #3636). But if you could generalize this to allow building upload services as plugins (see #1422) that would be a _huge_ step!

**Comment by MiniDigger** [comment]
This sounds like something a plugin should provide. 
The lounge should expose an interface a plugin can implement to provide, plugin can implement that provider interface and register it, and the user can select a provider by specifing the name in the config, and additionally options for that provider (username, password, api keys, whatever)

**Comment by osm** [comment]
Yeah that makes sense, I will fix that as soon as I can

**Comment by MaxLeiter** [comment]
Closing, as this won't be accepted before more discussion is had. @osm, feel free to ping me (nick is same as my github name) in #thelounge on irc.freenode.net if you want to work on the plugin implementation.

**Pull request closed without merging**
