### PR TITLE
Add shrug to codebase

### PR DESCRIPTION
**Pull request by Nek-**
Problem: god, the command shrug was absent
Solution: adding it 👍 ✨ ✌️

Please notice that awesome refactoring ✨ for the echo message function that avoids code duplication. (this is the stuff that makes it appear in local after sending it)

### CODE REVIEW

**Comment by xPaw** [comment]
There's a shortcuts plugin you can use to do this.

**Comment by Nek-** [comment]
Excuse me but what do you mean?

**Comment by xPaw** [comment]
https://github.com/MiniDigger/thelounge-plugin-shortcuts

**Comment by MiniDigger** [comment]
Basically, we shouldnt fill the Core codebase with stuff like this, thats why the plugin api was created.
If we have shrug, ppl will want a tableflip too. And then another emoji.
Instead, you can just add whatever you want via plguins, my shortcut plugin makes the really easy.

**Comment by Nek-** [comment]
Except shrug is by default on slack and discord as well.

**Comment by MiniDigger** [comment]
That command was "inherited" from shout, so it wasnt added by the current maintainer team.
https://github.com/thelounge/thelounge/commit/dbcf26d1bd07c8512fec25fbe1a05bac6228a31c

**Pull request closed without merging**
