### PR TITLE
Show quit dialog when using /quit

### PR DESCRIPTION
**Pull request by Nachtalb**
Beforehand it only showed the dialogue when quitting via the context menu. This also adds the possibility for the server to ask for dialogues.

https://user-images.githubusercontent.com/9467802/119228481-7b292980-bb13-11eb-97b2-e5c2fc9ad2b3.mp4

### CODE REVIEW

**Comment by MaxLeiter** [comment]
I believe we never added it to /quit because typing /quit is very deliberate, whereas it's pretty easy to fat-thumb the disconnect. I'm not against this PR, just worried it adds unnecessary complexity

**Comment by Nachtalb** [comment]
> I believe we never added it to /quit because typing /quit is very deliberate, whereas it's pretty easy to fat-thumb the disconnect. I'm not against this PR, just worried it adds unnecessary complexity

The thing is you can very easily accidentally type `/quit` and hit enter due to autocomplete. `/quit` is quite a strong action as it removes all network settings and the whole message backlog without any way to undo it.

**Comment by brunnre8** [comment]
ok, here's my two cents:

In my opinion we should just remove /quit entirely.
You very very rarely want to delete a network. That's a thing that doesn't need to be done quickly.

I'd rather have a single command that leaves absolutely no confusion as to what it does and we have that in `/disconnect` for the use case which might be more frequent, naming to disconnect from a network.

**Comment by dgw** [comment]
#4194 seems relevant here. I'll say again, I don't think `/quit` ever _should_ have deleted all network settings from TL. It should only be an alias to `/disconnect`.

**Comment by fnutt** [comment]
Some people likes commands instead of going through menus to remove networks and logs related to it. I'm perfectly fine with this PR, and would very much like to see it merged, please. It will prevent us from accidently doing something that we don't want, but still have the /quit command working as intended in the first place.

If we want to remove, adjust or find other (hopefully better...) solutions later down the road, we can do that later.

**Comment by brunnre8** [comment]
I don't get that argument fnutt, when do you ever want to delete a network from the chat input?

**Comment by fnutt** [comment]
When you don't want to be on the network anymore? Why keep logs for a network you are not on anymore?

Instead of right clicking on the network name -> choose "remove", you can instead type /quit.

**Pull request closed without merging**
