### PR TITLE
Add `try`/`catch` to `localStorage` methods

### PR DESCRIPTION
**Pull request by adamus1red**
Return null when attempting to get an item from localStorage
Now with 66% less commits.

REF: #2699

### CODE REVIEW

**Comment by dgw** [comment]
For future reference, you can merge, edit, and remove commits from an existing PR (such as #2700) with `git rebase`. https://help.github.com/articles/about-git-rebase/ Then `git push -f` to the branch.

**Comment by xPaw** [comment]
Can you make it a single comment on top of the file instead of 4 separate ones?

**Comment by xPaw** [comment]
Remove the comment from `set` too (and add the info in the top comment you added)

**Comment by xPaw** [comment]
@adamus1red Could you please update comments as per my suggestion?

**Comment by astorije** [comment]
Thanks and congrats on your first PR, @adamus1red!
If you're interested, make sure to get some contributor stickers [here](https://docs.google.com/forms/d/e/1FAIpQLSfv2K0o59Z5y09-ejZlVO8nPerylA8BXZ2tfpV6OJi8wCg2Vw/viewform) 😁

**Pull request merged**
