### PR TITLE
Pointer cursor hovering nicks in userlist

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by astorije** [comment]
I would rather turn these into `button`s (which would make the cursor come for free). Do you want to look into this instead, @MaxLeiter?
Also, @xPaw, is there any reason that would make us prefer the current `span role="button"` instead? It seems to me these should be actual buttons.

**Comment by xPaw** [comment]
I believe there were problems with actual buttons. For one, I think it's not possible to select button text.

**Comment by astorije** [comment]
That's fine, we made the userlist un-selectable anyway.

**Comment by xPaw** [comment]
Nicks in chat though.

**Comment by astorije** [comment]
This change is for `#chat .names .user`, and `.names` is only in userlist I believe.

**Comment by xPaw** [comment]
We use one template everywhere nick is rendered, so yeah.

**Comment by astorije** [comment]
Ah, that makes sense. Thanks for clarifying.

**Comment by McInkay** [comment]
How about using links? They make more sense semantically than a button, and they get the cursor for free, but still allow selecting of the text.

**Comment by astorije** [comment]
> How about using links?

@MaxLeiter, @xPaw?

**Comment by xPaw** [comment]
I don't think using `<a>` will solve anything we haven't already (besides showing a useless href preview in browser when hovering over nicks).

**Comment by astorije** [comment]
That makes sense.

**Pull request merged**
