### PR TITLE
Adding sign-up feature

### PR DESCRIPTION
**Pull request by thisisdarshan**
This PR is to add a sign-up feature.  It is intended to support local and LDAP sign-up both.

### CODE REVIEW

**Comment by christer88** [comment]
This one needs to be optional in config file, and default to false. I'm certain not everyone would like a sign-up feature to be open for the public.

**Comment by dgw** [comment]
Needs fixes to linter errors and a proper commit message.

**Comment by MaxLeiter** [comment]
Not a fan of #signup-signin - shouldn’t the sign up button be #signup and the signin button be #signin?

**Comment by McInkay** [comment]
Sorry about the long time it is taking to look at this, @thisisdarshan .

There has been a lot of change recently, is this something you would be able to rebase and fix, or are you not around to do it anymore? 

We will be porting the client side code to vue (#2636) so it might be easier to rewrite than fix this current one. Let me know what you think.

**Comment by xPaw** [comment]
I will close this PR (for now at least) due to inactivity.

Sorry for that, I think we will need to discuss this feature a little more before actually implementing it. Stuff like abuse and rate limiting needs to be considered.

An issue for reference and discussion: #914

**Pull request closed without merging**
