### PR TITLE
Add server config api

### PR DESCRIPTION
**Pull request by McInkay**
- [x] Add documentation to site
- [x] Rebase

### CODE REVIEW

**Comment by McInkay** [comment]
This os a real simple one, but could be really useful. Allows plugins to view and change config. 

I guess the question issss...is there anything in this we want to make sure we black out. Don't want plugins reading passwords for example.

**Comment by xPaw** [comment]
> Don't want plugins reading passwords for example.

They will be able to just use `fs` and read the file directly?

**Comment by McInkay** [comment]
> They will be able to just use fs and read the file directly?

Good point, but do we want to give them an official way? Or do we not care?

**Comment by xPaw** [comment]
@McInkay document this in the site repo.

**Comment by McInkay** [comment]
Will do that ...  probably Monday.

**Comment by McInkay** [comment]
Done. thelounge/thelounge.github.io#212

**Pull request merged**
