### PR TITLE
Add sponsor button config

### PR DESCRIPTION
**Pull request by jake-walker**
#3233

### CODE REVIEW

**Comment by xPaw** [comment]
Thanks for the PR.

I think we can simplify it to:
```
github: [xPaw, astorije, McInkay] # Current maintainer team
open_collective: thelounge
```

**Comment by jake-walker** [comment]
Ok, the comments have been removed and other lines removed.

**Comment by xPaw** [comment]
Actually, this probably should be added in the global repo: https://github.com/thelounge/.github

**Comment by xPaw** [comment]
I created it there, thanks for your PR though!

https://github.com/thelounge/.github/commit/3c8ccf37251d6a5e33a6513356447f37fd2e193a

**Pull request closed without merging**
