### PR TITLE
Replace all uses of `fs-extra` with native methods

### PR DESCRIPTION
**Pull request by xPaw**
The `recursive` option was added in Node 10.12.0.

https://github.com/jprichardson/node-fs-extra/blob/a149f822c387958caba7333ad2830615ab8b078f/lib/mkdirs/make-dir.js#L95-L106

### CODE REVIEW

**Comment by lpil** [comment]
Hello! I believe this may solve a problem I'm having with thelounge 4.1.0 crashing at boot due to the users directory already existing on my server.

When will this code be released as a new version? Thanks :)

**Comment by xPaw** [comment]
What crash are you having exactly? 4.1 did not change anything in regards to user folders.

**Comment by lpil** [comment]
The problem isn't specific to 4.1, sorry if I was unclear.

I get this on boot as my server already has /var/opt/thelounge/users as I back it up and restore it when I create a new server.

```
Error: EEXIST: file already exists, mkdir '/var/opt/thelounge/users'                                                                                                                                                                                                       at Object.mkdirSync (fs.js:753:3)                                                                                                                                                                                                                                      at Object.mkdirsSync (/usr/local/share/.config/yarn/global/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)                                                                                                                                                       at initalizeConfig (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/command-line/start.js:37:10)                                                                                                                                                       at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/command-line/start.js:17:3)                                                                                                                                                    at Command.listener (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:315:8)                                                                                                                                                                       at Command.emit (events.js:189:13)                                                                                                                                                                                                                                     at Command.parseArgs (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:654:12)                                                                                                                                                                     at Command.parse (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:474:21)                                                                                                                                                                         at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/command-line/index.js:55:9)                                                                                                                                                     at Module._compile (internal/modules/cjs/loader.js:689:30)  
```

**Comment by xPaw** [comment]
What OS is that?

You can test the master version, if the error still persists, make a new issue.

**Comment by lpil** [comment]
I'm using the alpine docker container on Ubuntu Linux.

Is there a master image for me to test with?

**Comment by lpil** [comment]
> EDIT: Could it be this? jprichardson/node-fs-extra#625

Ah yes I think that is it! Thank you

**Pull request merged**
