### PR TITLE
style: Put user colors into the smallest possible scope

### PR DESCRIPTION
**Pull request by brunnre8**
The only thing that cares about user colors is the user component. Putting a class value on the chat component seems to be the wrong place.

This also allows us to remove various css selectors so that we don't need to be that specific.
After all whatever has that class needs to be colored, we don't care where it is.

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Are we using this CSS in multiple places or we can move it into a component?

**Comment by brunnre8** [comment]
theoretically component,  but I really don't want to put colors there.

It should be easy for themes to be created and to override colors, as is we are using way to much colors in way to deep selectors.

My actual goal is to remove all colors from the default style and just have layout there 

All colors and fancy styles should be pushed into the themes

**Comment by brunnre8** [comment]
and iiuc component CSS gets mangled no? that's how they do the scoping?

That'd make it hard to override

**Comment by MaxLeiter** [comment]
`<style>` is global by default, `<style scoped>` is scoped

**Review by MaxLeiter — APPROVED** [review]

**Pull request merged**
