### PR TITLE
Make menu state consistent on desktop and mobile; fix sliding on desktop

### LINKED ISSUE #2572: Sidebar has weird behavior on desktop viewports with touch
Demo on an 9.7" iPad (I am dragging my finger towards the right-hand side in the chat messages container): https://streamable.com/zw7cc

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #2572.

Second part of my fixes for 18:9 mobile phones 😇

### CODE REVIEW

**Comment by astorije** [comment]
Mind fixing conflicts?

**Comment by astorije** [comment]
Default on desktop is now no sidebar, I don't think we should do that. Any way we can prevent it?

**Comment by xPaw** [comment]
@astorije Are you sure? How did you test it?

**Comment by astorije** [comment]
I'm not sure, let me test that again cleanly. I've been switching branches for testing back and forth so who knows. Every time I opened TL, channel list was closed. I'll test some more.

**Comment by astorije** [comment]
It overall works well, but removing the animation on "desktop" makes menu swiping on landscape mode of wide phones (like Pixel 2 XL, iPhone X, etc.) weird:

Portrait | Landscape
--- | --- 
portrait | landscape

What's your take on this?

**Comment by xPaw** [comment]
That's by design, we discussed this on IRC (don't remember with who though).

**Comment by astorije** [comment]
Yeah, let's go with that for now and see how we can improve that. I do expect tablets and large phones in landscape mode to act funny, but it's not the most common scenario so maybe not something we'll get bug reports for?

**Pull request merged**
