### PR TITLE
Upgrade to webpack 4; tracking pr

### PR DESCRIPTION
**Pull request by xPaw**
- [x] Cannot read property 'handlebarsLoader' of undefined
  - Related to https://github.com/pcardune/handlebars-loader/pull/153?
- [x] warning " > babel-loader@7.1.2" has incorrect peer dependency "webpack@2 || 3".
- [x] warning " > istanbul-instrumenter-loader@3.0.0" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
  - https://github.com/webpack-contrib/istanbul-instrumenter-loader/pull/79
  - https://github.com/webpack-contrib/istanbul-instrumenter-loader/pull/84
  - https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/85
  - https://github.com/thelounge/thelounge/pull/2307
- [x] warning " > mocha-webpack@1.0.1" has incorrect peer dependency "mocha@^2.4.5 || ^3.0.0 || ^4.0.0".
  - https://github.com/zinserjan/mocha-webpack/pull/204
- [x] warning " > mocha-webpack@1.0.1" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
  - https://github.com/zinserjan/mocha-webpack/pull/211
- [x] warning " > mocha-webpack@1.1.0" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
- [x] warning " > webpack-dev-server@2.11.1" has incorrect peer dependency "webpack@^2.2.0 || ^3.0.0".
- [x] warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
- [x] `yarn test:browser` is empty

### CODE REVIEW

**Comment by astorije** [comment]
A bunch of PRs in related projects are opened, I am now subscribed to all of them I believe, so I'll post here when I get notified.
Now let's see what projects come through.

Ah, the joys of major upgrades in the Webpack world...

**Comment by astorije** [comment]
`yarn test:browser` produces nothing, not sure why :/

**Comment by xPaw** [comment]
@astorije I'm still getting this warning, even though their package.json specifies webpack 4 as peer dependency. Ideas?

```
warning " > mocha-webpack@1.1.0" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
```

**Comment by astorije** [comment]
@xPaw, you mentioned `yarn test:browser` works for you. Mine doesn't, super weird. Could you confirm you do _not_ see this on your end:

screen shot 2018-03-21 at 20 15 28

**Comment by MaxLeiter** [comment]
@astorije: can confirm same issue on macOS

**Comment by xPaw** [comment]
@astorije Yeah, it's empty for me too now...

**Comment by xPaw** [comment]
I think this is ready expect for the `test:browser` being busted.

**Comment by astorije** [comment]
I was pretty much giving up, ended up spending way too much time on this, but it turns out a simple `*` fixed `test:browser`. Be damned, Webpack.

**Pull request merged**
