### PR TITLE
Add fading scroll overflows in channel list, user list, and main chat, and make user list sections sticky

### PR DESCRIPTION
**Pull request by astorije**
I initially did this as part of #2315 but there are small stupid issues on Firefox (and I'm expecting others in Edge), and I might be doing this entirely wrong anyway.

It actually looks pretty cool and I think it's worth that I spend more time on it, but it doesn't have to block #2315, however I'm opening this earlier to get feedback or suggestions for improvements.

### CODE REVIEW

**Comment by xPaw** [comment]
I looked at this in the revamped theme PR, and I didn't like that much. Do we really need these gradients?

A sharper look is better, imo.

**Comment by astorije** [comment]
Do you really find anything less sharp though? This PR shouldn't affect that. Like, anything blurry or other bugs? (I noticed there is a bug in user list with the last nick per category at the moment)

The gradients are a nice cue that there is more than what's currently visible. It's especially helpful on devices that have no scrollbars. Reasoning is similar to gradients in lieu of ellipsis.
It also helps with accessibility, especially around cognitive disorders.

That said, I am having second thoughts about the main window, especially because it scrolls from bottom, and it's the main item on the screen, focusing the attention already.
I do see a value in having this in channel list and user list though. Thoughts?

For comparison, we are using goddamn Jira at work and every week I can see someone confused about the sidebar and its scrolling content, which was truly made by the devil. A simple cue like a gradient, an icon, whatever setting up expectations and reducing surprises would make it _so much_ better.

**Comment by astorije** [comment]
Yikes, thanks for noticing that @williamboman. I'll fix #2315!

**Comment by astorije** [comment]
@xPaw, I extracted the sticky position into #2643 because I figured it wasn't controversial and buggy like the fading.

What's your take on this, are you opposed to this altogether, or you think it just needs to be improved? For example, I could get rid of it in main content but keep it in channel/user lists which is where I find it actually useful.
If you have other suggestions/ideas, I'm all ears. If you just think it's garbage at all, then I'll ditch it I guess 🤷‍♂️

**Comment by xPaw** [comment]
@astorije This might cause more problems due to #2448.

**Comment by astorije** [comment]
Fair enough. I'll close for now, can play with this again in a few <enter unit of time> when #2448 is resolved and/or browsers get their 💩 together. It would probably take me a few cycles to get the scrollbar thingy right, and I don't want to waste time if it's causing other issues I can't fix.

**Pull request closed without merging**
