### PR TITLE
Add HTML lang and labelled-by field to upload

### PR DESCRIPTION
**Pull request by MaxLeiter**
Found the errors using the [WAVE extension](https://wave.webaim.org/extension/).

Until we have localization, the UI language is always English, so I think it's fine to set the lang to en.

### CODE REVIEW

**Comment by xPaw** [comment]
While it's true UI is English, the chat messages may not be, that's why I avoided adding the lang attribute.

**Comment by MaxLeiter** [comment]
Then I think it should be set to empty string so it's explicitly unknown.

However, I believe if the provided content is English the language should be en

**Comment by xPaw** [comment]
Is there an attribute we could set on chat content to indicate unknown language?

**Comment by MaxLeiter** [comment]
We could set lang=“” (unknown) on the chat window or a container if they
don’t contain English elements. If not, we could declare it on each message.

**Comment by xPaw** [comment]
Does that actually work, if you declare it on the chat window?

**Comment by MaxLeiter** [comment]
From the spec:

> To determine the language of a node, user agents must look at the nearest ancestor element (including the element itself if the node is an element) that has a lang attribute in the XML namespace set or is an HTML element and has a lang in no namespace attribute set

https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes

So I think it would work fine

**Review by xPaw — APPROVED** [review]

**Pull request merged**
