### PR TITLE
Renamed username forms name to match standards

### LINKED ISSUE #1740: Firefox won't offer to save password
Currently when loggin in with username and password there is no popup asking me if I want to remember the login data in my browser password directory. It would be great if lounge could setup the elements accordlingy so this works :).

### PR DESCRIPTION
**Pull request by MaxLeiter**
ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

I believe this fixes #1740

### CODE REVIEW

**Comment by richrd** [comment]
I dont see any standard for the `name` attribute. Looks like you meant to use the `autocomplete` attribute instead?

**Comment by xPaw** [comment]
@dgw Can you check if this actually fixes that issue?

**Comment by dgw** [comment]
@xPaw I'll test if I get a chance, but we should also ping @gsantner as the original reporter.

**Comment by xPaw** [comment]
@MaxLeiter I was worried something would be missed in the rename, and it is, e.g. in `auth()` function call.

Could you revert the rename and just keep the `autocomplete` option? It should fix the password saving without potentially breaking anything.

**Comment by xPaw** [comment]
Playing around with this, this doesn't fix saving passwords in Firefox.

**Comment by xPaw** [comment]
Superceded by #2741

**Pull request closed without merging**
