### PR TITLE
Remove scripts/changelog.js in favor of GitHub's automatic changelog generation

### LINKED ISSUE #1375: SOCKS proxy support over corporate network
ref (https://github.com/erming/shout/issues/690)

Currently I'm behind corporate firewall and I would like to run Lounge IRC and connect to an external IRC outside the network. Is it possible to connect Lounge IRC over a SOCK proxy to the external IRC?

### PR DESCRIPTION
**Pull request by MaxLeiter**
There's now a button when creating GitHub releases that offers to auto-generate a changelog. The result won't be as fancy or in-depth, but it would be easier to curate. I'm open to closing w/o merging if people feel strongly about keeping the existing script. 

Here's what github generates for 4.3 (with no editing by me, and note that I don't think releases renders the inline PR information, it instead just links the #PR):

## What's Changed
* Skip video/audio embeds if og:type exists but does not specify it by @xPaw in https://github.com/thelounge/thelounge/pull/4040
* Add version support for packages. by @McInkay in https://github.com/thelounge/thelounge/pull/4041
* Add .vscode settings and suggested extensions by @xPaw in https://github.com/thelounge/thelounge/pull/4042
* Update dependency pretty-quick to v3 by @renovate in https://github.com/thelounge/thelounge/pull/4045
* Update dependency @babel/core to v7.11.4 by @renovate in https://github.com/thelounge/thelounge/pull/4043
* Update dependency tlds to v1.209.0 by @renovate in https://github.com/thelounge/thelounge/pull/4046
* Detect `image/avif` as an image by @xPaw in https://github.com/thelounge/thelounge/pull/4047
* Add HTML lang and labelled-by field to upload by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4051
* Add enterkeyhint on chat input and topic save by @xPaw in https://github.com/thelounge/thelounge/pull/4055
* Always use multi-prefix modes by @xPaw in https://github.com/thelounge/thelounge/pull/4060
* Update dependencies by @xPaw in https://github.com/thelounge/thelounge/pull/4087
* Make `add` and `reset` CLI commands scriptable by @supertassu in https://github.com/thelounge/thelounge/pull/4090
* Do not generate and send client certificate unless SASL EXTERNAL is requested by @xPaw in https://github.com/thelounge/thelounge/pull/4093
* Update vue monorepo by @renovate in https://github.com/thelounge/thelounge/pull/4094
* Add extended join information to join message by @GewoonYorick in https://github.com/thelounge/thelounge/pull/4105
* Add ignore option to contextmenu by @GewoonYorick in https://github.com/thelounge/thelounge/pull/4104
* Fix breaking GIFs while removing metadata by @Nachtalb in https://github.com/thelounge/thelounge/pull/4110
* Add gopher and gemini to the commonSchemes by @Willamin in https://github.com/thelounge/thelounge/pull/4151
* Update dependency eslint-plugin-vue to v7.5.0 by @renovate in https://github.com/thelounge/thelounge/pull/4141
* Update dependency eslint to v7.19.0 by @renovate in https://github.com/thelounge/thelounge/pull/4140
* Update dependency dayjs to v1.10.4 by @renovate in https://github.com/thelounge/thelounge/pull/4139
* Update dependency copy-webpack-plugin to v6.4.1 by @renovate in https://github.com/thelounge/thelounge/pull/4138
* Update dependencies by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4155
* Update actions/setup-node action to v2 by @renovate in https://github.com/thelounge/thelounge/pull/4129
* Add network specific leave message by @Nachtalb in https://github.com/thelounge/thelounge/pull/4116
* Upgrade to socket.io v3 by @xPaw in https://github.com/thelounge/thelounge/pull/4112
* Configure server ping timeout to 60 seconds by @emilyst in https://github.com/thelounge/thelounge/pull/4171
* Update dependency eslint to v7.21.0 by @renovate in https://github.com/thelounge/thelounge/pull/4170
* Update dependency css-loader to v5.1.1 by @renovate in https://github.com/thelounge/thelounge/pull/4169
* Update dependency commander to v7.1.0 by @renovate in https://github.com/thelounge/thelounge/pull/4168
* Update babel monorepo by @renovate in https://github.com/thelounge/thelounge/pull/4167
* Update dependency sqlite3 to v5.0.2 by @renovate in https://github.com/thelounge/thelounge/pull/4142
* v4.3.0-pre.1 release by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4174
* Add prefetchMaxSearchSize to override limit for link previews by @brunnre8 in https://github.com/thelounge/thelounge/pull/4135
* Show give/revoke modes and kick on other modes than +o by @mitaka8 in https://github.com/thelounge/thelounge/pull/4176
* Fix client crash when opening a user context menu in query by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4181
* Update dependency @fortawesome/fontawesome-free to v5.15.3 by @renovate in https://github.com/thelounge/thelounge/pull/4183
* NetworkForm: s/away message/leave message/ by @brunnre8 in https://github.com/thelounge/thelounge/pull/4193
* Update dependency chai to v4.3.4 by @renovate in https://github.com/thelounge/thelounge/pull/4184
* Update babel monorepo by @renovate in https://github.com/thelounge/thelounge/pull/4182
* Update dependency eslint to v7.23.0 by @renovate in https://github.com/thelounge/thelounge/pull/4076
* Update dependency commander to v7.2.0 by @renovate in https://github.com/thelounge/thelounge/pull/4185
* Settings: show label for nick autocompletion postfix by @brunnre8 in https://github.com/thelounge/thelounge/pull/4195
* `client/views` -> `client/components` in README by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4196
* Improved handling of empty userdata by @Nachtalb in https://github.com/thelounge/thelounge/pull/4190
* Add proper filename to the content-disposition header by @Nachtalb in https://github.com/thelounge/thelounge/pull/4187
* Restrict what the browser should try to autocomplete by @Nachtalb in https://github.com/thelounge/thelounge/pull/4192
* Support animated webp images by @Nachtalb in https://github.com/thelounge/thelounge/pull/4186
* Update dependency chalk to v4.1.1 by @renovate in https://github.com/thelounge/thelounge/pull/4208
* Update babel monorepo to v7.14.0 by @renovate in https://github.com/thelounge/thelounge/pull/4207
* Message Search: Re-Rebase + Fixes / Adjustments by @Nachtalb in https://github.com/thelounge/thelounge/pull/4197
* Message search by @richrd in https://github.com/thelounge/thelounge/pull/3664
* Classes for channels in list with unread counts and highlights by @sha1sum in https://github.com/thelounge/thelounge/pull/4214
* Allow text drag & drop into text fields by @Nachtalb in https://github.com/thelounge/thelounge/pull/4212
* Update dependency ua-parser-js to v0.7.24 [SECURITY] by @renovate in https://github.com/thelounge/thelounge/pull/4216
* Fix missing users in userlist after removing searchinput by @Nachtalb in https://github.com/thelounge/thelounge/pull/4221
* Improve inline audio file support by @Nachtalb in https://github.com/thelounge/thelounge/pull/4210
* Update dependency postcss to v8.2.10 [SECURITY] by @renovate in https://github.com/thelounge/thelounge/pull/4223
* Fill inputhistory on channel load and more message load by @Nachtalb in https://github.com/thelounge/thelounge/pull/4206
* Add new "/search query" command to open the search window by @Nachtalb in https://github.com/thelounge/thelounge/pull/4213
* Add support for JPEG XL image previews by @TheDecryptor in https://github.com/thelounge/thelounge/pull/4219
* Change the IRC server to Libera.Chat by @mhajder in https://github.com/thelounge/thelounge/pull/4238
* Render styling for colored host masks by @angerson in https://github.com/thelounge/thelounge/pull/4235
* MessageSearchForm: do not focus input if search is closed by @brunnre8 in https://github.com/thelounge/thelounge/pull/4242
* Update dependencies by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4252
* install: allow installation of local packages by @brunnre8 in https://github.com/thelounge/thelounge/pull/4251
* Revert "Fix load more button hidden behind search form" by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4259
* Fix not overriding config options with -c by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4262
* Display server-originated notices to channels in the channel window by @BradleyShaw in https://github.com/thelounge/thelounge/pull/4260
* Differentiate WALLOPS from NOTICE by @BradleyShaw in https://github.com/thelounge/thelounge/pull/4264
* Toggle recent mentions popup with alt+m by @bl1nk in https://github.com/thelounge/thelounge/pull/4258
* Update dependencies by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4265
* Bump irc-framework to 4.11 by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4266
* Add support for SOCKS (closes #1375) by @Mstrodl in https://github.com/thelounge/thelounge/pull/4211
* Initial accessibility improvements by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4201
* Add /umode support by @JeDaYoshi in https://github.com/thelounge/thelounge/pull/4274
* Fix userlist's wrong position on mobile devices by @JeDaYoshi in https://github.com/thelounge/thelounge/pull/4279
* Add warning for HTTPS requirement on notifications by @JeDaYoshi in https://github.com/thelounge/thelounge/pull/4280
* Fix nick-less messages from servers by @JeDaYoshi in https://github.com/thelounge/thelounge/pull/4277
* Only scroll history when cursor is on first or last row by @Nachtalb in https://github.com/thelounge/thelounge/pull/4205
* Update dependencies by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4281
* Optimise modes based on ISUPPORT by @JeDaYoshi in https://github.com/thelounge/thelounge/pull/4275
* properly track user modes for context menu by @brunnre8 in https://github.com/thelounge/thelounge/pull/4267
* Revert #4186 "Support animated webp images" by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4287
* Update dependency pretty-quick to v3.1.1 by @renovate in https://github.com/thelounge/thelounge/pull/4304
* Update dependency stylelint to v13.13.1 by @renovate in https://github.com/thelounge/thelounge/pull/4307
* Update dependencies by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4312
* Do not condense single messages by @supertassu in https://github.com/thelounge/thelounge/pull/4313
* Update dependency socket.io-client to v3.1.3 by @renovate in https://github.com/thelounge/thelounge/pull/4318
* Update dependency ua-parser-js to v0.7.28 by @renovate in https://github.com/thelounge/thelounge/pull/4319
* Update dependency webpack-hot-middleware to v2.25.1 by @renovate in https://github.com/thelounge/thelounge/pull/4321
* Update dependency web-push to v3.4.5 by @renovate in https://github.com/thelounge/thelounge/pull/4320
* Vertically center topic editing input in Safari. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4325
* Add keyboard shortcut for help screen by @NoahvdAa in https://github.com/thelounge/thelounge/pull/4315
* Prevent sporadic rounding of search input on iOS. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4328
* Allow network list reordering via touch. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4326
* Two-finger swipe now switches windows (#3901) by @itsjohncs in https://github.com/thelounge/thelounge/pull/4324
* client/Mentions: change button copy to "Dismiss all" by @williamboman in https://github.com/thelounge/thelounge/pull/4322
* Use SortableJS 1.14.0. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4330
* Clean up global listener in Sidebar component. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4331
* Fix sporadic rounding on message search bar. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4333
* Clarify description of prefetchMaxSearchSize. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4338
* Prevent autocomplete for highlight settings by @brunnre8 in https://github.com/thelounge/thelounge/pull/4337
* Fix authenticated proxy by @Nachtalb in https://github.com/thelounge/thelounge/pull/4341
* bump vulnerable ua-parser-js version by @hom3chuk in https://github.com/thelounge/thelounge/pull/4343
* Move font assignment of password reveal icon by @deejayy in https://github.com/thelounge/thelounge/pull/4342
* Update dependency mime-types to v2.1.33 by @renovate in https://github.com/thelounge/thelounge/pull/4349
* Update dependency linkify-it to v3.0.3 by @renovate in https://github.com/thelounge/thelounge/pull/4348
* Enable Android's context menus in network list. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4332
* Csp by @brunnre8 in https://github.com/thelounge/thelounge/pull/4344
* Improve responsiveness of channel name and topic. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4340
* Prevent round and white search styling in iOS 15. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4352
* Small cleanup of messageStorage/sqlite. by @itsjohncs in https://github.com/thelounge/thelounge/pull/4345
* Add more plugin functionality by @brunnre8 in https://github.com/thelounge/thelounge/pull/4329
* Allow wildcards in hostmask by @brunnre8 in https://github.com/thelounge/thelounge/pull/4351
* Bump required node version to 12.x and add 16.x builds by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4356
* Allow escape key to close search bar and search page by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4364
* Mentions esc by @brunnre8 in https://github.com/thelounge/thelounge/pull/4365
* Switch to thelounge/Sortable fork for Sortable.js by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4368
* Revert "Preserve location on first and last line when scrolling through inputs" by @MaxLeiter in https://github.com/thelounge/thelounge/pull/4367

## New Contributors
* @supertassu made their first contribution in https://github.com/thelounge/thelounge/pull/4090
* @GewoonYorick made their first contribution in https://github.com/thelounge/thelounge/pull/4105
* @Nachtalb made their first contribution in https://github.com/thelounge/thelounge/pull/4110
* @Willamin made their first contribution in https://github.com/thelounge/thelounge/pull/4151
* @emilyst made their first contribution in https://github.com/thelounge/thelounge/pull/4171
* @mitaka8 made their first contribution in https://github.com/thelounge/thelounge/pull/4176
* @sha1sum made their first contribution in https://github.com/thelounge/thelounge/pull/4214
* @TheDecryptor made their first contribution in https://github.com/thelounge/thelounge/pull/4219
* @mhajder made their first contribution in https://github.com/thelounge/thelounge/pull/4238
* @angerson made their first contribution in https://github.com/thelounge/thelounge/pull/4235
* @BradleyShaw made their first contribution in https://github.com/thelounge/thelounge/pull/4260
* @bl1nk made their first contribution in https://github.com/thelounge/thelounge/pull/4258
* @Mstrodl made their first contribution in https://github.com/thelounge/thelounge/pull/4211
* @JeDaYoshi made their first contribution in https://github.com/thelounge/thelounge/pull/4274
* @itsjohncs made their first contribution in https://github.com/thelounge/thelounge/pull/4325
* @NoahvdAa made their first contribution in https://github.com/thelounge/thelounge/pull/4315
* @hom3chuk made their first contribution in https://github.com/thelounge/thelounge/pull/4343
* @deejayy made their first contribution in https://github.com/thelounge/thelounge/pull/4342

**Full Changelog**: https://github.com/thelounge/thelounge/compare/v4.2.0...v4.3.0

### CODE REVIEW

**Comment by termermc** [comment]
In general I think depending on a proprietary system is worse than just using your own tooling

**Comment by MaxLeiter** [comment]
The custom script uses the github API, @termermc

**Comment by termermc** [comment]
lol I am dumb

**Comment by xnaas** [comment]
As it is, that's...very verbose. I feel like dependabot/renovate stuff, in particular, could be condensed significantly to something like:

* X number of dependencies updated (#4348, #4348, etc.)
* X security patches by @renovate (#4223, etc.)

The rest of it is just looks a lot of repetition, based on how GitHub renders stuff (at least, [this is what I see](https://user-images.githubusercontent.com/8271327/142969618-75ef9551-7533-4379-bb9d-6c3f011ce427.png)).

**Comment by dgw** [comment]
> The rest of it is just looks a lot of repetition, based on how GitHub renders stuff (at least, this is what I see).

Ah yes, the unilateral rendering change that should have been a new syntax instead and annoyed a bunch of maintainers whose task lists and other old issues suddenly had mountains of redundant text, the disruptiveness of which GitHub has never (AFAIK) acknowledged.

Interesting that the changelog tool generates this format, unless expanding inline issue/PR references is disabled in release descriptions.

**Comment by MaxLeiter** [comment]
> Interesting that the changelog tool generates this format, unless expanding inline issue/PR references is disabled in release descriptions.

I believe that is the case

**Comment by brunnre8** [comment]
You're the maintainer who has to do it, in other words no pushback of any kind from my side.
You get to choose your tools.

**Comment by xPaw** [comment]
Yeah as usual with these automatic generation its very verbose. How does that compare to our tool? (Did it break?)

**Comment by xPaw** [comment]
Perhaps if configured it can get much more closer to what we had: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

**Comment by MaxLeiter** [comment]
Closing for now, not too many benefits and would require us to work on the changelog previewer in settings.

**Pull request closed without merging**
