### PR TITLE
Conversation layout for the main chat window

### PR DESCRIPTION
**Pull request by astorije**
Alright, this is the last overall visual change that I am planning for v3.0, and it focuses on the main chat layout (which was left alone in previous PRs).

screen shot 2018-06-18 at 00 35 26

screen shot 2018-06-18 at 00 37 49

In short:

- Instead of a table layout, messages are now displayed in a "conversation layout".
- When multiple messages are sent by a same user in a row (not interrupted by status messages), they are grouped together.
- User modes now have a UI through small badges next to the nicks, in lieu of `@`, `+`, etc.
- All of the above is completely cancellable (and tweakable) via custom CSS.

Now, just like #2315, I know not everyone will like that, but I hope no one will be upset at this proposal. I really have tried my best at making a maximum of people happy (see custom CSS provided below), but obviously I am open to make things better.
I realize that this is not a layout traditional IRC clients usually go for. It is however a direction all modern chats I have encountered have adopted over the last couple years (Discord, Telegram, Slack, Rocket.Chat, HipChat, Riot, etc.). I think overall this is a UX improvement.

Some concerns people may have:

### Does this reduce message density?

Yes, no doubt. In my tests, depending on the channel (Is it crowded or mostly status messages? Are people mostly talking with brief messages or is it more talkative? etc.), I noticed between 10% and 20% less messages on screen overall.
That said, I find it overall improves readability, and I had less mental efforts to make to follow a long discussion after coming back on a lot of messages.

### I hate it. Can we have a settings for this?

No. Maintaining several layouts in the core project adds a substantial amount of work on the core team, increases the risk of breaking things, and imposes people who open PRs to think about what they're adding/fixing in multiple scenarios.

If people hate it because it's imperfect, then it can and should be improved. The layout on `master` was not done in one day, and had at least 2 rewrites since we started. I'm not pretending this is going to be perfect at merge time or that nothing should be changed, but it's a starting point.

If people hate it because they simply preferred how something was before, I have tried to make this as flexible as possible:

- All the changes can be "reverted" with custom CSS, all provided below.
- I can think of a few customizations that can be made solely with custom CSS as well, I provided some below.
- Due to these 2 points, someone could decide to own and maintain a package whose job is to revert some part of the layout, or tweak it in some way. That way, we can still have multiple layouts without having to maintain it in core, we get help from the community.
- [`thelounge-theme-classic`](https://github.com/thelounge/thelounge-theme-classic) is meant to be a complete replica of v2.7.1 look. When this PR is ready, I will open a PR there that "reverts" everything for that theme.

### Is this 100% ready?

As of this writing, no. I have a few things I need to tackle, but it's in the most part what I was going for. I'm opening this unfinished to have early reactions so I can integrate as much feedback as I can in upcoming design.

If you see something that seems clearly broken, don't assume I went for this on purpose, it's likely that it's, in fact, broken, so let me know :)
On the top of my head, there are a few things I have just not even started to approach yet, but I am probably forgetting some so feel free to comment and I'll tackle them:

- [x] Notices
- [ ] Server window
- [x] Copy-paste
- [ ] `/me` messages aren't great
- [ ] Loading from history
- [x] Whois response
- [ ] Highlights have poor paddings (when non-highlighted and highlighted messages are mixed with same-sender)
- [ ] Channel list, ban list, ignore list

# Custom CSS snippets

These are meant to _just work_ with the changes on this PR. When it gets merged, if anything looks off, let me know and I'll fix.
If you can think of something else you'd like me to come up with, post here and I'll do my best.

### I don't like merging same-sender messages together

<details>
<summary>Snippet</summary>

```css
#chat .same-sender {
  margin-top: initial;
}

#chat .same-sender .from,
#chat .same-sender .time,
#chat .same-sender .mode-badge {
  display: inline;
}
```

</details>

Before | After
--- | ---
screen shot 2018-06-22 at 00 51 54 | screen shot 2018-06-22 at 00 51 13

### I don't like the mode badges, bring back the prefixes!

<details>
<summary>Snippet</summary>

```css
#chat .mode-badge {
  display: none;
}

#chat .from .mode {
  display: initial;
}
```

</details>

Before | After
--- | ---
screen shot 2018-06-22 at 00 53 28 | screen shot 2018-06-22 at 00 54 17

### I want to see timestamp for all messages

⚠️ This is very hacky (and probably buggy), but it illustrates one possibility to show all timestamps. I have no doubt someone smarter than me will come up with something better :)

<details>
<summary>Snippet</summary>

```css
#chat .same-sender .time {
  display: initial;
  float: left;
  margin-left: 10px;
  margin-top: 5px;
}

#chat .message:not(.same-sender) .time {
  float: left;
  left: 10px;
  top: 24px;
}

/* FIXME: This is surely not working correctly when displaying seconds in timestamps */

#chat .message:not(.same-sender) .from {
  margin-left: -28px;
}

#chat .message:not(.same-sender) .content {
  text-indent: 40px;
}
```

</details>

Before | After
--- | ---
screen shot 2018-06-22 at 01 12 16 | screen shot 2018-06-22 at 01 11 54

### I like the conversation layout, but I need more density

<details>
<summary>Snippet</summary>

```css
.messages .msg {
  line-height: 1.2;
}

#chat .msg {
	padding-top: 3px;
	padding-bottom: 3px;
}

#chat .same-sender {
	margin-top: -6px;
}
```

</details>

Before | After
--- | ---
screen shot 2018-06-26 at 23 44 07 | screen shot 2018-06-26 at 23 44 11

### I hate _everything_, you fool!

This cancels everything this PR does. No Before/After screenshots, because it really just is "master vs this PR" :)

_(⚠️ Snippet needs a refresh to reflect latest changes to this PR)_

<details>
<summary>Snippet</summary>

```css
#chat .msg {
	display: flex;
	padding-top: 0;
	padding-bottom: 0;
}

#chat .msg:not(.message) {
	padding-left: 0;
	padding-right: 0;
	text-align: left;
}

#chat .from,
#chat .time,
#chat .content {
	padding-top: 3px;
	padding-bottom: 3px;
}

#chat .from,
#chat .time {
	font-size: 1em;
	flex: 0 0 auto;
}

#chat .time {
	order: -1;
	padding-left: 10px;
	width: 55px;
}

#chat.show-seconds .time {
	width: 75px;
}

#chat .from {
	font-weight: normal;
	text-align: right;
	width: 134px;
	overflow: hidden;
	white-space: nowrap;
}

#chat .from,
#chat .message .from {
	padding-right: 10px;
}

#chat .mode-badge {
	display: none;
}

#chat .from .mode {
	display: initial;
}

#chat .same-sender {
	margin-top: initial;
}

#chat .same-sender .from,
#chat .same-sender .time {
	display: inline;
}

#chat .content {
	border-left: 1px solid #f6f6f6;
}

#chat .msg:not(.message) .content {
	padding-left: 10px;
	padding-right: 10px;
}

#chat .condensed-summary {
	margin-left: 189px;
}

#chat.show-seconds .condensed-summary {
	margin-left: 209px;
}

@media (min-width: 480px) {
	/* Fade out for long usernames */
	#chat .from {
		padding-left: 10px;
		-webkit-mask-image: linear-gradient(to left, transparent, black 10px);
		mask-image: linear-gradient(to left, transparent, black 10px);
	}
}
```

</details>

### CODE REVIEW

**Comment by christer88** [comment]
I fucking love this PR, @astorije! BIG BIG thumbs up! This is exactly what I've been waiting for.

**Comment by xPaw** [comment]
How much does this break existing themes (e.g. Solarized)?

**Comment by Raqbit** [comment]
Amazing PR, @astorije! It looks really cool! Also I like how you're keeping the option to revert to the old layout, as I'm sure other people like IRC in a condensed way.

**Comment by christer88** [comment]
https://github.com/thelounge/thelounge/pull/815

**Comment by richrd** [comment]
It does look good but I have to say I'm one of those people that prefer the original formatting :thinking: 
I know this new layout is how all the modern chats are doing it but I'm not sure that means that it is objectively better in all cases. For me msg density is almost a key feature. I know you already said no to a setting to toggle it, but I feel that it would still be the ideal way to do it (slack has this as an option).

> Maintaining several layouts in the core project adds a substantial amount of work on the core team, increases the risk of breaking things, and imposes people who open PRs to think about what they're adding/fixing in multiple scenarios.

This is understandable, if this won't be toggleable I will create a package with the revert CSS, but even in that case the same maintenance burden exists, just in a different place. I'm also not sure how to make the package toggleable from the settings. I'm afraid the package will need to be fixed now and then if/when the classic layout breaks due to changes in core or themes. The timestamps, status messages and previews already have settings.

Anyway, just my 2 cents and thanks for providing the revert CSS, it's comforting to know that I can just copypaste it in to get the layout I like :)

**Comment by astorije** [comment]
Good feedback, thanks everyone!

> How much does this break existing themes (e.g. Solarized)?

For themes that do not customize the main message window layout (which from what I could tell is most if not all themes out there), this change _should_ simply switch to the conversation layout without breaking stuff.

For those themes, "reverting" this PR (hashtag sad) _should_ simply mean dropping the snippet posted above or the changes that I'll put in Classic theme.
I think a more forward-looking approach would be to leave the conversation layout in themes, and maintain/provide a "table layout package" so that people can choose what they prefer. That said, it's up to the package authors :)
(I do realize there is a bit of getting used to, but it would be lovely if authors gave it a few weeks before deciding to revert because they definitely don't like rather than reverting right away. Just my 2c obviously 🙂)

@xPaw, I just tried this PR with your theme on, no extra CSS, and it's _pretty_ good. Of course it's a completely different layout so one likes or dislikes, but I'm not seeing anything clearly broken:

screen shot 2018-06-26 at 19 26 19

_PSA: If you maintain a theme with special customizations around the main chat window layout, let me know as I'd like to try and see how it looks / if it breaks anything._

> For me msg density is almost a key feature.

In UX, generally speaking, we try to solve the problem of "I have too much data on my screen". So while I understand the need for some people to have a compact view, the problem of having too little density is pretty unique.
If losing a bit of density increases readability, it's worth it IMO, assuming the default density is acceptable. Then we can provide ways to make it more compact or less compact to people's preferences, but that's a future consideration IMO (in the meantime, custom CSS and themes are here to help).

> I know you already said no to a setting to toggle it, but I feel that it would still be the ideal way to do it (slack has this as an option).

Keep in mind that Slack has hundreds of employees and received millions of $$$ in funding, so I think they can afford maintaining extra options compared to us 😁
In fact, I have just tried their "compact layout" and it's not nearly as polished as the "clean layout": timestamp and message are misaligned, multilines are weirdly padded, etc. So this is precisely what I would like to avoid, having multiple ways to do this, having to maintain it ourselves, and over time make one (or several, or all) look poorer and poorer.

> but even in that case the same maintenance burden exists, just in a different place.

Oh, absolutely! To be clear, I am not saying that not doing this in core means less work for everyone, I perfectly know this is moving the responsibility to the community, and this is on purpose :)
This is for the same reason than extracting themes into separate repos, and what I have said above: we are a very small, free-time-based team, not a fully funded company, and this is a community project.

> I'm also not sure how to make the package toggleable from the settings.

It's not possible at the moment, but we've mentioned this in the past. At the moment, custom CSS packages are simply enabled if installed, but it would be nice if users could turn on/off from the client settings.

**Comment by RockyTV** [comment]
Can I suggest removing the mode/join/part messages from center and using the same alignment as the rest of the chat? It looks weird when it's in the middle and for me it looks like it's misaligned (top margin is not the same as the bottom one).

Also, [could you try out the theme I'm developing](https://github.com/RockyTV/lounge-onedark)? There shouldn't be any breaking changes at all to the layout, I just based it off the Zenburn theme that The Lounge has.

**Comment by astorije** [comment]
> For me msg density is almost a key feature.

@richrd, I know you said you dislike this altogether anyway, but if that's useful to you or anyone else, I added a custom CSS snippet to increase the density of messages on screen (and, funny thing, there are more messages showing up with that snippet + conversation layout than there are on `master` for a similar example).

> Can I suggest removing the mode/join/part messages from center and using the same alignment as the rest of the chat? It looks weird when it's in the middle

This is how it looks like:

&nbsp; | Before (centered) | After (left aligned)
--- | --- | ---
Collapsed | screen shot 2018-06-26 at 23 52 05 | screen shot 2018-06-26 at 23 53 07
Expanded | screen shot 2018-06-26 at 23 52 10 | screen shot 2018-06-26 at 23 54 32

What do you think? The idea being centering it was to avoid disrupting the flow of messages too much.
When your eyes read a conversation, they go left to right until the end of the message, then jump a line and focus on the left-hand side. Status messages are mentally challenging because they cause you to start reading something irrelevant. Because IRC, it's very very often that these status messages interrupt conversations.
I'm not saying they're useless obviously which is why we have them on by default, just that they add noise to conversations in general.

For this reason, I think I still prefer the centered version, but I'm open to alternatives to help improving the conversation flow. What about right-aligning? Making the condensed status messages smaller (e.g. same as nick+timestamp)? Any other ideas?

(Playing with this did show me an incorrect left/right padding in expanded status messages however, so thanks for this, fixed!).

> for me it looks like it's misaligned (top margin is not the same as the bottom one).

Can you clarify which margins you are talking about? I'm not seeing it some maybe I'm not looking at the right place.

> Also, could you try out the theme I'm developing?

A couple things to adjust, but overall it looks pretty decent to me:

screen shot 2018-06-27 at 00 32 01

Nice color set! 👏
I'm assuming you haven't published to npm yet because v3 is not out, so I had to git clone it. I suggest you add the `thelounge` and `thelounge-theme` so it shows up [in this list](https://github.com/topics/thelounge).
Also, I noticed you have a looot of color overrides, you might want to leverage CSS variables. We started adding a couple, so that may save you some troubles as well!

**Comment by dgw** [comment]
Perhaps predictably, I'm in the camp of users who will likely install a package (or custom CSS) to undo this as soon as it's put in a (stable) release. One of the reasons I don't like to use "modern chats" is the lower message density. Ever since the last Gmail redesign, my display density has never been set higher than "Comfortable" (and is at this moment set to "Compact"). I don't like excessive scrolling. (I'd also point out that Discord, too, provides a density choice. Not that I use their app—my Discord use runs almost exclusively through BitlBee, so I am by no means an expert on their UX decisions…)

> Can I suggest removing the mode/join/part messages from center and using the same alignment as the rest of the chat?

I second this. For markers like the date headers it makes sense to center them because they're meant to break up the message stream. But joins/parts/quits/modes are part of the message stream, even if condensed, and I don't think they should break it up.

While I'm here, I'd like to point out some nice touches I've seen in other IRC clients, specifically, for consideration as this layout update is finalized. This is just for the sake of throwing out ideas; I don't expect any of these ideas to be taken as-is and incorporated!

Probably my personal favorite style for an IRC client is Equinox, for Textual. (Me using Textual as an example is totally cliché at this point, isn't it? I guess @astorije and I have something in common: We both have chat apps we really like! :laughing:) It hides the nickname for same-sender messages, yes—but the main reason I bring it up here is as possible inspiration for the handling of timestamps. Equinox floats the message timestamp off to the right of the message, keeping it visible at a glance but reducing the perceived number of columns from three (timestamp, nick, message) to two (nick, message). In the years I've been using that style, it's felt like a nice middle ground between the tabular feel of "traditional IRC" and the overly loose (to me) layouts of newer apps like those mentioned in the top comment.

Equinox uses some cheeky JavaScript (Textual styles are just HTML, CSS, and JS, as is The Lounge's front-end) to fade out the nick if it's the same as the previous message, which is neither here nor there. It's a neat gimmick, that's all. But I really appreciate how the deduplication effect is achieved without sacrificing the number of chat lines visible. Between that and the timestamps, I think we have—if not inspiration for The Lounge's default direction, then at least the basis for a theme or CSS package. I might even get working on it once 3.0 goes stable, who knows!

**Comment by christer88** [comment]
I’m supporting astorije. I like hos ideas and reasonings behind his decisions.

Let’s get modern! Other themes can revert this as they prefer to.

**Comment by juhokuu** [comment]
After the pure block of gold that is #2315, this is jarring. 

This is a good look for mobile, because what else are you going to do with the limited screen real estate, but the thought of having to parse this wall of text on a regular basis is depressing. Not only is it a mess visually, but you have to actually focus and think who's the sender in the very first screenshots. Personally, I use Slack and Discord *in spite* of this -- it's not a selling point.

To offer at least something constructive: left aligning joins, quits etc. seems preferable to centering them; they break the flow of the view when centered. Especially when there's many of them in a row, all of different length.

**Comment by GewoonYorick** [comment]
I love it @astorije I've been waiting for this to come to The Lounge. Can't wait to see it in a next (pre) release! :)

**Comment by McInkay** [comment]
Bumped to 3.1 as discussed in irc. We'll try and get this merged early in 3.1 to get feedback from more users and to catch any issues that sneak in.

**Comment by xPaw** [comment]
I'm closing this PR for now, as it effectively needs to be restarted from scratch on Vue, and astorije has limited time.

**Comment by ronilaukkarinen** [comment]
I'm looking for the conversation layout to implement to my themes, at least for mobile. What's the current process to achieve this? Is there any themes out there that support this feature in the newest version? Been searching for ages and finally stumbled upon this PR and its dead ends just to see it's from many years ago... Anything new about this alternative layout? Where to look more?

**Comment by ronilaukkarinen** [comment]
It seems this is rather easy to do CSS-only. Only thing that is "missing" is the operator badge, but I like the prefix so it doesn't bother me.

This came out pretty nice:

Screen-Shot-2021-02-26-01-02-16 76

My `Custom stylesheet` with [midnight.css](https://github.com/ronilaukkarinen/thelounge-theme-modern) (please forgive the importants, I'm lazy while testing things out):

```
@media (max-width: 700px) {
  .messages .msg {
    font-size: 17px !important;
  }
  .from {
    font-size: 17px !important;
  }
  .time {
    font-size: 15px !important;
    align-self: flex-start;
    line-height: 1.9;
  }
}


/* Conversation layout, only on mobile */

@media (max-width: 700px) {
  #chat .msg[data-type="message"] {
    flex-wrap: wrap !important;
  }

  #chat .msg[data-type="message"] .content {
    max-width: 90%;
  }

  #chat .msg .time {
    position: absolute;
    right: 10px;
  }

  #chat .msg+.msg.previous-source .time,
  #chat .msg+.msg.previous-source .from {
    display: none !important;
  }

  #chat .msg[data-type="message"] .from {
    padding-left: 10px !important;
    padding-top: 5px !important;
    padding-bottom: 5px !important;
    width: 100% !important;
    text-align: left !important;
    display: flex !important;
  }

  #chat .msg:not([data-type="message"]) .from {
    display: none;
  }

  #chat .msg:not([data-type="message"]) .from::before {
    display: none;
  }

  #chat .msg:not([data-type="message"]) .content {
    border: 0 !important;
    padding-left: 10px !important;
    opacity: .5;
    max-width: 90%;
  }
  
  #chat .content {
    padding-left: 10px !important;
    border: 0 !important;
  }
}
```

With this media query the conversation layout is visible only on mobile and the regular layout on desktop 👍 

Thanks for awesome work and ideas!

**Comment by richrd** [comment]
I also once did this in just CSS as a fun exercise and I have it as a gist here. I think it looked better at the time but I'm not sure anymore.
https://gist.github.com/richrd/ad0e1ce6bf03b4c492841b7e65c31390

Your CSS looked good when I pasted it into the custom CSS of my instance (which isn't even the latest version at the moment). I should upgrade it some time soon.

**Comment by ronilaukkarinen** [comment]
@richrd Thanks! i have even improved version [here](https://github.com/pulinairc/thelounge-themes), the conversation layout is only present on Midnight themes on mobile only. I have improved it almost daily. Fixed it to work with date markers, links, etc. I love it on mobile.

**Pull request closed without merging**
