### PR TITLE
Improved condensing and testing

### PR DESCRIPTION
**Pull request by metsjeesus**
Its same code as #1047 . Probably way more complicated that it should be.  Made some test cases too, to show how it works. Maybe use unicode icons instead of english text, so we can skip the translation there.
Lazy as i am, its still work in progress,

### CODE REVIEW

**Comment by astorije** [comment]
Hey @metsjeesus, how much work do you estimate there is left on this?

**Comment by metsjeesus** [comment]
It all depends what and how things are condensable.  What i need is workable examples, what messages and in what order produce the specific result.  Test cases, like the mocha examples there or just post it as free text. I struggle find a elegant way to show kicks, bans and role changes.

**Comment by christer88** [comment]
As discussed with metsjeesus on IRC, I'm posting my example of how I think it may be done:

→ joins
← quit/kick/bans/kills
↔ peeked in/reconnected
user ⇒ new-nick
⧆ user modes

Channel modes are not condensed as they are important for everyone in the channel and shouldn't be hidden.

**Examples of the above:**

**(1)** → Testuser1, Testuser2, Testuser3 and Testuser4 joined

**(2)** ← Testuser1, Testuser2, Testuser3 and Testuser4 quit

**(3)** ↔ Testuser1 and Testuser2 peeked in

**(4)** Testuser sets channel mode to +f 3:5

**(5)** Testuser1 sets user mode +o on Testuser1

**(6)** ⧆ Testuser1 +o and Testuser2 -x

**(7)** → Testuser1 (⇒ Testuser1-newnick), Testuser2 and Testuser3 joined

**(8)** → Testuser1 (⧆ Testuser1 +o), Testuser2 and Testuser3 joined

**(9)** → Testuser1, Testuser2, Testuser3, Testuser4 and 10 others joined

**(10)** ← Testuser1, Testuser2, Testuser3, Testuser4 and 10 others quit

**Comment by christer88** [comment]
**(11)** ← Testuser1 (⇒ Testuser1-newnick), Testuser2, Testuser3 and 10 others quit

**(12)** → Testuser1 (⇒ Testuser1-newnick) and Testuser2 joined, Testuser8 ⇒ Testuser8-newnick

**Comment by christer88** [comment]
Slightly modified version with different symbols:

⇒ joins
⇐ quit/kick/bans/kills
⇔ peeked in/reconnected
user → new-nick
⧈ user modes

Channel modes are not condensed as they are important for everyone in the channel and shouldn't be hidden. Also, there are few channel mode changes.

**Examples of the above:**

**(1)** **⇒** Testuser1, Testuser2, Testuser3 and Testuser4 joined

**(2)** **⇐** Testuser1, Testuser2, Testuser3 and Testuser4 quit

**(3)** **⇒** Testuser1, Testuser2, Testuser3, Testuser4 and 10 others joined

**(4)** **⇐** Testuser1, Testuser2, Testuser3, Testuser4 and 10 others quit

**(5)** **⇔** Testuser1 and Testuser2 peeked in

**(6)** Testuser1 sets channel mode to +f 3:5

**(7)** Testuser1 sets user mode +o on Testuser1

**(8)** **⧈** Testuser1 +o, Testuser2 -x and Testuser3 +v

**(9)** **⇒** Testuser1 (Testuser1 **→** Testuser1-newnick), Testuser2 and Testuser3 joined

**(10)** **⇒** Testuser1 (**⧈** Testuser1 +o), Testuser2 and Testuser3 joined

**(11)** **⇐** Testuser1 (Testuser1 **→** Testuser1-newnick), Testuser2, Testuser3 and 10 others quit

If possible, and if wanted, we can merge them together to save space:
**⇒** Testuser1 (Testuser1 **→** Testuser1-newnick) and Testuser2 joined  **🞄**  Testuser8 **→** Testuser9-newnick  **🞄**  **⧈** Testuser6 +o, Testuser7 -x and Testuser8 +v

**Comment by metsjeesus** [comment]
## Version 3 (Minimized)
Very minimized version with different logic.
User modes are read as nick change.
Icons should be bigger.

⤽  Joins
⤼ Quit/kick/bans/kills
⇔ Peeked in 
⇎ Reconnected
→ Nick change
→ User mode

(1) ⤽ Testuser1, Testuser2, Testuser3, Testuser4

(2) ⤼ Testuser1, Testuser2, Testuser3, Testuser4

(3) ⤽ (Testuser1, Testuser2, Testuser3, Testuser4  ... +10)

(4) ⤼ (Testuser1, Testuser2, Testuser3, Testuser4  ... +10)

reconnecting
(5) ⇔ Testuser1, Testuser2
peeked in
(5.1) ⇎ Testuser1, Testuser2

(6) Testuser1 sets channel mode to +f 3:5

(7) Testuser1 → @Testuser1

(8) Testuser1 → @Testuser1, Testuser2 → %Testuser2, Testuser3 → +Testuser3

(9) ⤽ Testuser1 → Testuser1-newnick, Testuser2, Testuser3

(10) ⤽ @Testuser1, Testuser2, Testuser3

(11) ⤼ (Testuser1 → Testuser1-newnick, Testuser2, ... +10)

**Comment by McInkay** [comment]
Hey, @metsjeesus, sorry we've taken so long to respond to this. It hasn't been a huge priority, and we've been unable to agree on whether we even want this feature. However, now I think it's time to start nudging this along, and I think we probably do want this feature, as in many cases it will be useful. A few thoughts.

1. I don't think we should show all the information all the time. Let's take a look at how IRC cloud does this:



This is horrible, there is far too much information and it's not useful.

We have 3 options in this circumstances. Show it all, show only a few, show none of the names (and just show what we currently show).

The first, imo, is not useful as it's just a wall of names, and takes ages to see who you are looking for, it's probably easier to expand and see all the individual lines.

The second is unlikely to be useful in most cases.

The third is obviously not useful, but, I think, is tidier.

So I would suggest that we show the names if and only if there are ... say, less than 10 names. And if there are more, we fall back to what we currently do. 

The vast majority of cases that this will be shown, there will be 1 or 2 names, and you want to see at a glance who those names were. But when there are so many, its just not useful, imo.

2. I'm not convinced about the icons. I don't think they add any real information to the user, as they are all very similar, you need to look at the word anyway, and so they just take up space.

3. I've not had a look at the code, I'll do that later. This is just my thoughts about how the feature works in general.

**Comment by metsjeesus** [comment]
Just a example what it does currently. Your second option to show only a few is mostly useful on most cases. What i ask, is to find out and confirm those most case cenarios what usually happen and are useful.
http://prntscr.com/iinx26

**Comment by christer88** [comment]
I am strongly against your suggestion, @McInkay. It will make it pretty useless again... It should say the first 10 names, and if there are more we still show the first 10 names and "and x others". Look at @metsjeesus example.

**Comment by McInkay** [comment]
> It will make it pretty useless again...

Of course it won't make it "useless", that's hyperbole, it'll be useful in some cases (the vast majority of cases)

> Would prefer more than 5 atleast.

5 of each section, or 5 total?

> Look at @metsjeesus example.

I have looked at it, and I'm not sure showing the 3 in each section and then "and more" is actually useful in this case. The chances of the person you want being in that 3 is tiny, and it's causing more of the screen to be used up for something that has a tiny chance of actually being useful.

**Comment by christer88** [comment]
> Of course it won't make it "useless", that's hyperbole, it'll be useful in some cases (the vast majority of cases)
Well, it will hide so much information in so many cases I find it useless. Sorry.

> 5 of each section, or 5 total?
5 of each yes, at least!

> I have looked at it, and I'm not sure showing the 3 in each section and then "and more" is actually useful in this case. The chances of the person you want being in that 3 is tiny, and it's causing more of the screen to be used up for something that has a tiny chance of actually being useful.

Then bump the number to 10, and it will include the majority of the cases. It's not often it will show 50 nicks. Most times it will be maybe 10 people that joined, 4 that left, 3 peeked in and 2 had some mode changes.

**Comment by christer88** [comment]
The thing is - it needs to show the information we want to see, and not hide it. Hiding information very often only results in people having to expand the condensed message, or get so annoyed they turn the whole thing off so they can atleast see what is happening in the channel (as I did). Your example from IRCCloud is a bit hard to read yes, but your example is of a channel that has been idle for a week probably. This isn't the normal cases.

**Comment by christer88** [comment]
user4, user5, user6, user7, user8, user9, user10, user11, user12, user13, useer14 and 4 others peeked in | user15 and user16 reconnected | user17, user18 and user 19 joined | user20, user21, user22 and user23 quit | user1 (voiced), user2 (opped), user3 (opped)

**Comment by metsjeesus** [comment]
Ive used it for a long time, and i feel 3 is enough for most cases on active channels. 5 might be too much. Well, if there is alot of condensing, it can change from 5 to 3, that is possible too. On a non busy channel, it might get out of hand and might need shorter limit. 

Why 3 is enough, because it will show 3 recent names on condensing. 9 out of 10 times, that is enough relevant infromation you want to see.

**Comment by christer88** [comment]
@metsjeesus I don't see the reason for keeping it to just 3. 5 to 10 would make sense so we don't hide information that much.

**Comment by McInkay** [comment]
> 5 of each yes, at least!

Not 5 of each. That's far too many. I would say 10 total.

> Then bump the number to 10, and it will include the majority of the cases

I'm arguing that my suggestion already includes the majority of cases. 

> Hiding information very often only results in people having to expand the condensed message

This is condensing them, when you condense something it means you won't see all the information. That's the entire point of the feature. If you want to see all the information when there are a large number, you will have to expand.

We already agree that you can't always show all of it, because you are suggesting limiting it just with a higher number than I am. Now we are just disagreeing over how much we do that.

I won't argue this point much because I don't care enough, but I think having too much information devalues the feature and makes it annoying. If the other maintainers agree with you, then fine, I'll yield. 

However, let me try once more to convince you.

The most common situation to want to know this information in condensed form is this:

* Talking to someone
* Someone leaves the channel
* I want to see if the person that left the channel is the person I am talking to

The second most common situation (in my experience) is this:

* Talking to person a about person b
* Someone joins the channel
* I want to see if it's person b, because I don't want to say something I'll regret

The vast majority of other times that the condensed messages appear, I'm not wanting to see something at a glance, and the condensed messaging is not useful to me, so I expand. 

The 2 scenarios I'm talking about there will be 1 or 2, maybe 3 or 4 people that join/leave a channel and so we can show all the information then. 

I see no useful scenario where we have over 10 people joining/leaving and I actually want to see who joined/left without seeing everyone (in which case I will expand).

Can you give me a use case for when you would want that? I want to understand why you want this.

**Comment by christer88** [comment]
> Can you give me a use case for when you would want that? I want to understand why you want this.

**Comment by metsjeesus** [comment]
example... 5 user joined on a active channel what you are looking.

you could see, "user1, user2, user3, user4 and user5 joined"
or you could see change "user1, user2 and user3 joined" to
"user2, user3, user4 and 1 others joined" and then
"user3, user4, user5 and 2 others joined"

That is mostly enough relevant information while keeping it short.

**Comment by christer88** [comment]
> This is condensing them, when you condense something it means you won't see all the information. That's the entire point of the feature. If you want to see all the information when there are a large number, you will have to expand.

I disagree. Condensing doesn't mean hiding, it means to compress it... and compressing the text it still does if it shows more than just 10 people. Again, IRCCloud does it nicely, but in the insane scenarios (as you found an example of), yes it will not look so tidy with so much information. However, it's still condensed!

**Comment by metsjeesus** [comment]
I agree on @McInkay on this case, condensing will strip some information out and that is fine. Question is what is relevant information what you want to see even if condensing hides it. My suggestion was, put them on groups and show 3 of each group. Might work on on most of cases on active channel, but its not perfect on a idle channel.

**Comment by christer88** [comment]
@metsjeesus You are talking as if channels are active all the time with people chatting. This isn't true for a lot of the channels, yet it's nice to see what is actualy going on. There are **_MANY_** cases each day more than 3 people does something, before someone is talking again.

**Comment by McInkay** [comment]
You haven't explained your use case, @christer88, you just posted a bunch of screenshots. Please explain what they are meant to show. I'm not trying to be difficult here, but if we are going to decide on functionality, we need to have real reasons for it.

> I disagree. Condensing doesn't mean hiding, it means to compress it

We are hiding information, we don't show hostmasks, for example, we don't show timestamps for each of the joins, etc. To condense, you *need* to hide information.

> in the insane scenarios (as you found an example of)

It's not an insane scenario, it's a pretty common case for either netsplits (which happen easily on a weekly basis) or on channels that don't have much activity.

The fact of the matter is, the vast majority of people don't need (or want) to see all of the information if 20 people have joined/left since the last message. They just don't care. You are in the minority, and if that means you have to expand it, then so be it. The point of UX is to make it good for the vast majority of people, it can't be good for everyone.

> If you have anything more to do in the channel than this (e.g. being chanop/ircop, or just wants to know what is going on), showing just 10 isn't enough.

Are you seriously looking at every single join/part/mode change that goes on in your channels?

> There are MANY cases each day more than 3 people does something, before someone is talking again. 

Yup, there are. And in these cases, most people don't care what has happened. 

---

@metsjeesus I don't think we should decide the number we show based on x per group. If we say, 3, and all that happens is 5 people join, that's less than ideal. I think we should show x overall. So we say 10 names. That means that if there are 10 people joining, or 5 people joining and 5 people leaving, then we show all of that.

Then if there are more, I think we just fall back to what we had before. 

As I say, if @thelounge/maintainers don't think we should fall back to what we had before above the number, then that's fine, we can go with that.

**Comment by McInkay** [comment]
> May I please suggest a setting for this in /#settings under "Status messages", or in json config file?

That didn't take long. Nah, we won't be adding a setting for this.

We already have 3 ways of dealing with these messages

1. Show none
2. Show all
3. Show condensed

If the condensed view doesn't work for you, you can turn it off. I understand that you want a condensed view that works perfectly for you, but we can't have settings for absolutely everything. If you must have this functionality, you can do it on your own instance, and that's fine. But we won't be adding a setting for this. I am pro settings, but this is just too far for a setting.

**Comment by christer88** [comment]
@McInkay You might be right about my use case isn't the same as what everyone wants. Suggest making it a config/setting option so we can make everyone happy, since we clearly do not agree here and I can for sure say I'm not alone about my use case.

I do not agree about falling back to the current situation above 10. Then show "and X more" instead, please, since we atleast get to see most of the information.

**Comment by metsjeesus** [comment]
Example, user1_afk joins, changes name to user1 and gets voice from either a bot, other user or gives itself.

On this case, what is relevant information what you want to see? For me "user1_afk->+user joined" is enough. There are alot of different use cases and patters, what you want to see(example bans) and it is a matter of option how much you want to see and how much you want to hide.

For the unicode arrows, thats the idea of stripping out translations. Its not required, but makes it universal on all translations.

**Comment by christer88** [comment]
@metsjeesus I think having text saying what is happening makes most sense, since we have to make it work for people down to age 5 as well. TheLounge isn't just a client for the most advanced ones. We can translate the few words later with the localization PR.

Regarding showing bans, please don't condense them. Regarding condensing different stuff for the same user... well, I think it's nice, but for the simplicity and to get this PR approved, I suggest showing it individually - as in showing "userA joined | userA changed nick to userA2 |  userA2 (opped)

**Comment by McInkay** [comment]
> Suggest making it a config/setting option so we can make everyone happy, since we clearly do not agree here and I can for sure say I'm not alone about my use case.

I don't think this should be a config setting. I'm pretty sure @astorije will be with me on this, and I don't think @xPaw will care much, so this won't happen.

> I do not agree about falling back to the current situation above 10. Then show "and X more" instead, please, since we atleast get to see most of the information.

I am open to changing my mind about this, but I want to hear input from @thelounge/maintainers. I don't think showing that would give any real advantage, but I also don't think it would be the end of the world if we did it.

The important thing to me is that we don't show everything in all cases, as I do not want it to ever end up like the irc cloud screenshot I showed above as that's just horrible.

> Regarding showing bans, please don't condense them.

They already are condensed. 

---

> Example, user1_afk joins, changes name to user1 and gets voice from either a bot, other user or gives itself.

Yeah, the difficulty is figuring out all of the information from this, and what is even useful, that's a really complex problem. 

> There are alot of different use cases and patters, what you want to see(example bans) and it is a matter of option how much you want to see and how much you want to hide.

Yup, agreed, and we can't have settings for everything because that would become unweildy, and would lead to really complex code.

> For the unicode arrows, thats the idea of stripping out translations. Its not required, but makes it universal on all translations.

Yeah, I get that, but I'm not convinced they are obvious enough to be useful. Happy to be disagreed with on this. I think they are too small and too similar to be clear enough, personally.

**Comment by christer88** [comment]
> The important thing to me is that we don't show everything in all cases, as I do not want it to ever end up like the irc cloud screenshot I showed above as that's just horrible.

May I please suggest 20 then? It would atleast cover 99% of the cases for me where it's useful to see the information.

> Yeah, I get that, but I'm not convinced they are obvious enough to be useful. Happy to be disagreed with on this. I think they are too small and too similar to be clear enough, personally.

I agree about this. Let's stick with text which says exactly what has happen.

**Comment by McInkay** [comment]
> May I please suggest 20 then? It would atleast cover 99% of the cases for me where it's useful to see the information.

Are you still suggesting per section? 20 per section would be a ridiculous amount.

**Comment by christer88** [comment]
> Are you still suggesting per section? 20 per section would be a ridiculous amount.
In total 😁 , and above 20 we can do whatever you like, as 20 I'm pretty sure would cover most cases for most people anyway. It would however be nice if it could say "and X others" though, but I'm not going to fight over this if it's set to 20 in total.

**Comment by metsjeesus** [comment]
@McInkay , i just explain what it currently does, its not perfect and it needs adjustment. We have 7 groups, what will group the messages into one. Every group can show 3 last ones, so total of 21 names will be ideally shown on maximum. Well, it shows currently all nick changes what is a exeption the the 3 name rule. It will show most recent names based on activity, so you get relevant informaton on active channel. Problem is, if some info comes in to those condensing, placements of every name change, what is mildly annoying. Other then that, it is short enough even on worst case, its not perfect.

Showing x last activity has same problem, if something adds to the condensing, everything changes. Thing to consider.

**Comment by McInkay** [comment]
> Showing x last activity has same problem, if something adds to the condensing, everything changes. Thing to consider.

Yeah, I get that it makes it more complicated, but it feels like a nicer user experience to me because then if there are, say, 5 people joining and nothing else, it would seem silly to only show 3 of those names. Does that make sense?

Could you investigate implementing a total of 20, and above that fall back to what we currently have, and we can see how it feels? 

I'm not convinced about 20, it feels quite big. But I'm happy to try it out and see how it goes. I think it's still best to fall back above that amount because otherwise it just gets even bigger when you add "and x more".

**Comment by christer88** [comment]
@McInkay You do have a point with maximum amount for entire condensed message instead of maximum for each group. I'm happy for your suggestion above with 20 to be implemented. 👍

**Comment by metsjeesus** [comment]
@McInkay Its deninitely doable. Some problems on edge cases. For simpicity, if maximum names 3, and 3 people join in the channel and then 3 different people left in the channel. How the result should look?

I would like to make a rule, that maximum x different names will be shown on condensed message. That would make sense. What happens on after x messages is hard to figure out.

2 major things what currenlty take room, are mode changes and nick changes. Maybe we can figure out how to make it minimal and useful. Do nick change count as 1 name or 2?, do mode change count 0, 1, or 2 names?

**Comment by christer88** [comment]
Having maximum amount of nicks shown instead of maximum amount of "changes" would work as well. I do wonder how you'll solve this when someone changes nick though. Does it count as 1 or 2 nicks out of the maximum 20?

**Comment by McInkay** [comment]
> For simplicity, if maximum names 3, and 3 people join in the channel and then 3 different people left in the channel. How the result should look?

Good question. Let me have a think about that, but I'm thinking around balancing it between the 2. So in the case you say, we would have 2 in 1 and 1 in the other. But yeah, that becomes a bit more complicated.

> What happens on after x messages is hard to figure out.

Let's start with falling back to what we had before, as that's the simplest for just now.

> Do nick change count as 1 name or 2?, do mode change count 0, 1, or 2 names?

Oh goodness all of this is just becoming more complicated. 2 names, I think for nick changes. I would say probably keep mode changes out of it just now. We should ideally show the most next to their name, but that can be a different PR, and I don't think the change is massively necessary to show there.

**Comment by metsjeesus** [comment]
"+NewNick1 joined | +Nick1 changed nick to +NewNick1 | +NewNick1 opped"
that line is too big for my taste. I prefer something like
"+NewNick1>@Nick1"

Or maybe simple mode change on giving, removing opping, "@Nick + @" "Nick - @"
all its matter of taste, and im not good on tasting stuff:)

**Comment by McInkay** [comment]
I'd probably say, if someone joins, then changes nickname, just show them as joining with the new nickname.

**Comment by metsjeesus** [comment]
Ther is a reason why i have programmed it like 4 times from scratch. or was it 5? I made it TESTABLE with mocha, so test cases, test cases, test cases. 

@McInkay if you take time and make a own version of the examples above(that big list of 11 cases), that would be big help. It wont need to be perfect on the first try.

**Comment by christer88** [comment]
**(1)** Testuser1, Testuser2, Testuser3 and Testuser4 joined

**(2)** Testuser1, Testuser2, Testuser3 and Testuser4 quit

**(3)** Testuser1, Testuser2, Testuser3, Testuser4 and 10 others joined

**(4)** Testuser1, Testuser2, Testuser3, Testuser4 and 10 others quit

**(5)** Testuser1 and Testuser2 peeked in

**(6)** Testuser1 set channel mode to +f 3:5

**(7)** Testuser1 opped

**(8)** Testuser1 opped, Testuser2 voiced and Testuser3 voiced

**(9)** Testuser1-newnick, Testuser2 and Testuser3 joined

**(10)** @Testuser1, Testuser2 and Testuser3 joined

**(11)** Testuser1-newnick, Testuser2, Testuser3 and 10 others quit

**Merged together:**
Testuser1-newnick and Testuser2 joined | Testuser8 changed nick to Testuser9-newnick | Testuser6 opped, Testuser7 voiced and Testuser8 voiced

**Comment by christer88** [comment]
**(1)** @Testuser1-newnick,+Testuser2, Testuser5 and Testuser12 joined | %Testuser8 changed nick to %Testuser9-newnick | Testuser6 opped and +Testuser7 voiced | Testuser19 quit

**(2)** @Testuser1-newnick,+Testuser2, +Testuser9-newnick and Testuser12 joined | Testuser6 opped and +Testuser7 voiced

**(3)** @Testuser1-newnick and +Testuser2 joined | +Testuser9-newnick peked in | @Testuser1 set channel mode to +f 3:5

If total nicks > 20 in merged together examples above, then fall back to the current state with just listing how many has done what.

-------

Is the above examples something we can agree on, @McInkay?

**Comment by astorije** [comment]
Hey @metsjeesus and @christer88, sorry I didn't chime in earlier. I wanted to sync up with the rest of @thelounge/maintainers before voicing something, to make sure we were more or less on the same page.

Looking at this nicely detailed thread, I see quite a bit of complexity, and I think we can manage to remove some to keep this simple and still very useful.
I'm overall with @McInkay. Sorry if anything I say below heavily contradicts with something you guys have already discussed, but keep in mind that communication and decision-making over text can incur misunderstandings 😅

So this is my suggestion:

- If number of nicks in a status message is lower than N, expand those nicks:
  `alice and bob have joined the channel, charlie has quit, and dave has changed nick.`
- Above N, keep the current solution:
  `4 users have joined the channel, 5 users have quit, and 3 users have changed nick.`

A bit of details about why and how:

- I would keep N rather low (such as 5) because anything big is just cognitive overflow, and clutters the space and information on the rest of the screen. 20 is way too big in that regard, 10 would be an acceptable compromise (I still think it's too high but I'm fine to try with this and see how it goes).

- N would not be a setting. Keep things simple, and just make a decision. If people want more, they can via the "show all status messages" option.

- When there are more nicks than N, falling back to the current solution provides a few benefits:
  - There is no decision to make regarding how to balance number of nicks allocated per section. IMO when we start reaching this kind of considerations, we might ask ourselves if we didn't go a bit too deep and take a step back a bit. Not making this kind of balancing makes things much simpler.
  - There is no decision to make about which nicks to select (as in "alice, bob and 2 others...": why alice? why bob?). Should it be alphabetical? Order of status change? Most recent person who sent a message? This is endless :D Additionally, such report has limited value if only showing some nicks, in that I would probably have to expand anyway.

- Don't bother about special characters for separators or types of status messages. Just go with words, again for simplicity sake: icons would require some sort of tooltips, accessibility attributes, etc. Words work just fine, and I suggest keeping the current wording. Your work is about displaying nicks, take advantage of what we already have so we can focus on reviewing/merging this. We can always improve things later.

- If something is not trivial to "convert" (from not displaying nicks to displaying nicks), don't do it. For example, for the sake of this PR, modes can stay "summarized" and one needs to expand to get full info on modes. Trying to make everything perfect means it will be difficult to get it over the finish line. It seems to me like the prime candidate use case for this is having quick access to who recently joined and quit, and that's something your work can easily do. Things beyond that might just delay your goal, which is why I'm suggesting a more iterative approach.

Alright, I hope this makes sense and doesn't piss anyone off :) All suggestions above are meant to keep this easy to implement, test, review, merge, and use, while having something substantially better than `master`. It's all about good/perfect trade-offs :D
Let me know if any of this was unclear (again, text discussions + it's really really late here, make for easy misunderstandings!). 👋

**Comment by christer88** [comment]
I will comment on astorije's comment above later today. I don't agree with several things, but I do appreciate his comment on the PR. :)

**Comment by metsjeesus** [comment]
@astorije 
Good points, good ideas. Its something to discuss. And its conflicting a bit with @McInkay ideas:
`I want to see if the person that left the channel is the person I am talking to`
`I want to see if it's person b, because I don't want to say something I'll regret`

So im with N approach. But if you say this.
`4 users have joined the channel, 5 users have quit, and 3 users have changed nick.`
You dont see the names you want to see above mentioned reasons. That is bad.

I try to focus a bit the rules on condensing. Open for any changes, ideas. 
1. Every name will be shown once in condensing, nick changing counts as one name.
2. No matter how much you condense, every name must be shown when corresponding event happens. 
3. No more then N names and their last actions are shown on condensing. 
4. If there is a meaningful way to merge some events what happen often, merge them into one name.
5. Keep it on english.

And current master has condensing what works, so we have no restrictions to do it fast, we have time to think it trough.

Above mentioned rules could end up as a one feed group named "actions". 
`user1 and user2 joined, user3 and user4 reconnected, user5 and user6 quit, user7afk changed nick to user7, user8 opped, user9 voiced, user10 halfopped and 10 more actions`
and if newuser joins it ends up
`newuser, user1 and user2 joined, user3 and user4 reconnected, user5 and user6 quit, user7afk changed nick to user7, user8 opped, user9 voiced and 11 more actions`

**Comment by fnutt** [comment]
https://github.com/thelounge/thelounge/issues/1684

**Comment by McInkay** [comment]
Hey, we discussed and are going to close this just now. It'll need re-written in vue, and I think we need to have some more discussions around exactly how we want this to come out. 

I'm sorry for this, it obviously must be disappoing with all the work you have put in, but there's no point in it hanging around when the last thing was over 6 months ago.

Feel free to continue discussions about what we might want from this feature and/or start converting to vue. 

Thanks for the effort.

**Pull request closed without merging**
